"""initial_tables_v2

Revision ID: 363860405da4
Revises: 
Create Date: 2026-04-22 10:50:48.245875
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '363860405da4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazard_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_api', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity_weight', sa.Float(), nullable=False),
    sa.Column('geometry_geojson', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lng', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazard_zones_external_id'), 'hazard_zones', ['external_id'], unique=True)
    op.create_index(op.f('ix_hazard_zones_is_active'), 'hazard_zones', ['is_active'], unique=False)
    op.create_index(op.f('ix_hazard_zones_source_api'), 'hazard_zones', ['source_api'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('callsign', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('heading_deg', sa.Float(), nullable=False),
    sa.Column('cargo_type', sa.String(length=128), nullable=True),
    sa.Column('cargo_priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=256), nullable=True),
    sa.Column('destination', sa.String(length=256), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('route_polyline', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_callsign'), 'trucks', ['callsign'], unique=True)
    op.create_table('forecast_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('forecast_type', sa.String(length=64), nullable=False),
    sa.Column('forecast_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('hours_ahead', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_alerts_truck_id'), 'forecast_alerts', ['truck_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('hazard_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('proximity_km', sa.Float(), nullable=False),
    sa.Column('eta_to_hazard_min', sa.Float(), nullable=True),
    sa.Column('component_scores', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazard_zones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_hazard_id'), 'risk_events', ['hazard_id'], unique=False)
    op.create_index(op.f('ix_risk_events_truck_id'), 'risk_events', ['truck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_events_truck_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_hazard_id'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_forecast_alerts_truck_id'), table_name='forecast_alerts')
    op.drop_table('forecast_alerts')
    op.drop_index(op.f('ix_trucks_callsign'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_hazard_zones_source_api'), table_name='hazard_zones')
    op.drop_index(op.f('ix_hazard_zones_is_active'), table_name='hazard_zones')
    op.drop_index(op.f('ix_hazard_zones_external_id'), table_name='hazard_zones')
    op.drop_table('hazard_zones')
    # ### end Alembic commands ###
